// Mocks generated by Mockito 5.4.4 from annotations
// in task_management_app/test/domain/task/task_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_management_app/app/domain/failures/failures.dart' as _i5;
import 'package:task_management_app/app/domain/task/i_task_repository.dart'
    as _i3;
import 'package:task_management_app/app/domain/task/task.dart' as _i6;
import 'package:task_management_app/app/domain/task/task_form/task_form.dart'
    as _i8;
import 'package:task_management_app/app/domain/task/task_success/task_success.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i3.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, List<_i6.TaskModel>>>
      getTasks() => (super.noSuchMethod(
            Invocation.method(
              #getTasks,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AppFailure<dynamic>,
                        List<_i6.TaskModel>>>.value(
                _FakeEither_0<_i5.AppFailure<dynamic>, List<_i6.TaskModel>>(
              this,
              Invocation.method(
                #getTasks,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.AppFailure<dynamic>, List<_i6.TaskModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>> submit(
          _i8.TaskForm? form) =>
      (super.noSuchMethod(
        Invocation.method(
          #submit,
          [form],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>>.value(
            _FakeEither_0<_i5.AppFailure<dynamic>, _i7.TaskSuccess>(
          this,
          Invocation.method(
            #submit,
            [form],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>> editTask(
          _i8.TaskForm? form) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTask,
          [form],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>>.value(
            _FakeEither_0<_i5.AppFailure<dynamic>, _i7.TaskSuccess>(
          this,
          Invocation.method(
            #editTask,
            [form],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>> deleteTask(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>>.value(
            _FakeEither_0<_i5.AppFailure<dynamic>, _i7.TaskSuccess>(
          this,
          Invocation.method(
            #deleteTask,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure<dynamic>, _i7.TaskSuccess>>);
}
